### ISSUE TITLE
java.lang.ClassNotFoundException: com.demo.DemoMain

### ISSUE THREAD

**Issue by opjk** [formkiq/graalvm-native-plugin#8]
./openJFXdemo 
Exception in thread "main" java.lang.RuntimeException: java.lang.ClassNotFoundException: com.demo.DemoMain
	at javafx.application.Application.launch(Application.java:304)
	at com.demo.DemoMain.main(DemoMain.java:26)
Caused by: java.lang.ClassNotFoundException: com.demo.DemoMain
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
	at java.lang.Class.forName(DynamicHub.java:1292)
	at javafx.application.Application.launch(Application.java:292)
	... 1 more

**Gradle configruation**

```
apply plugin: "java"
apply plugin: "application"
apply plugin: "org.openjfx.javafxplugin"
apply plugin: "com.formkiq.gradle.graalvm-native-plugin"

javafx {
    version = "15"
    modules = ["javafx.base", "javafx.controls", "javafx.fxml"
//               , "javafx.graphics"
//               , "javafx.media", "javafx.swing", "javafx.web"
    ]
}

nativeImage {
    mainClassName = "com.demo.DemoMain"
    javaVersion = "java11"
    imageVersion = "20.3.0"
}
```

**Comment by mfriesen** [comment]
It looks like 'com.demo.DemoMain' is being look up via reflection. Graalvm does not support reflection out-of-the-box. In order to use reflection you need to specify a reflection config file (https://www.graalvm.org/reference-manual/native-image/Reflection/). If you look at the aws-lambda sample in the repository you'll see an example of how to do this. You can specify the reflection file as:
nativeImage { 
    ...
    reflectionConfig = "$buildDir/classes/java/main/META-INF/graal/reflect.json"
} 

You can also use the gradle annotation processor:
   annotationProcessor 'com.formkiq:graalvm-annotations-processor:1.0.0'

and the annotation "com.formkiq.graalvm.annotations.Reflectable;" annotation at the top of your class, will automatically generate the reflection config file for you.

Hope that helps you out.
